ENV["LC_ALL"] = "fr_FR.UTF-8"
#$Linux_default_network_interface = `ip route | awk '/^default/ {printf "%s", $5; exit 0}'`
#$Windows_Get-NetAdapter -Name * | %{ $_.name } | select-string -Pattern 'VMnet1'

Vagrant.configure("2") do |config|
    # Required version
    Vagrant.require_version ">= 2.3.1"
    # Update the plugins if not present
    if Vagrant.has_plugin?("vagrant-vbguest") then
        config.vbguest.auto_update = true
    end
    config.vm.box = "centos/7"
    config.vm.define "Docker"
    #config.vm.hostname = "exemple.com"
    config.vm.network "private_network", ip: "192.168.99.10"
    config.ssh.forward_agent = true
    config.vm.network "forwarded_port", guest: 22, host: 2222,
    auto_correct: true
    config.vm.provision :shell do |shell|
        shell.path = "install_tools.sh"
        shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end
    # Provider (vmware_desktop/virtualbox)
    # |p| Ignores provider config options, |v| Display Vagrant version
    config.vm.provider "vmware_desktop" do |v|
        # Settings VM
        v.gui = true
        v.memory = 8192
        v.cpus = 4
        # Disable linked clones
        v.linked_clone = false
    end
  end